services:
  # Frontend
  nuxt:
    build:
      context: .
      dockerfile: _.src/frontend/Dockerfile
      args: 
        - PROJECT=nuxt
    ports:
      - "3000:3000" # Nuxt development server runs on port 3000
    networks:
      - app-network
    volumes:
      - ./_.src/frontend/nuxt:/app # For live reloading during development
      - nuxt-node_modules:/app/node_modules

networks:
  app-network:
    driver: bridge

volumes:
  nuxt-node_modules: